[project]
name = "bilitickerbuy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bili-ticket-gt-python~=0.2.8",
    "gradio~=4.44.1",
    "gradio-calendar~=0.0.6",
    "gradio-log~=0.0.4",
    "install-playwright~=0.1.0",
    "loguru~=0.7.2",
    "ntplib~=0.4.0",
    "numpy~=1.26.4",
    "onnxruntime~=1.18.0",
    "opencv-python~=4.11.0.86",
    "pillow~=10.3.0",
    "playsound3~=3.2.2",
    "playwright~=1.46.0",
    "pydantic~=2.8.2",
    "qrcode~=7.4.2",
    "requests~=2.31.0",
    "retry~=0.9.2",
    "scipy~=1.15.2",
    "setuptools~=65.5.1",
    "tinydb~=4.8.0",
]
[tool.mypy]
disable_error_code = ["import-untyped"]
check_untyped_defs = true
