name: Python Release

on:
  push:
    tags:
      - 'v*.*.*'
#https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners
jobs:
  build:
    name: Build Executables
    runs-on: ${{ matrix.config.os.name }}
    strategy:
      matrix:
        config:
          - os:
              name: ubuntu-22.04
              filename: linux_amd64
          - os:
              name: ubuntu-22.04-arm
              filename: linux_arm64
          - os:
              name: macos-14
              filename: macos_arm64
          - os:
              name: macos-13
              filename: macos_intel
          - os:
              name: windows-latest
              filename: windows_amd64
    steps:
      - name: Checkout source
        uses: actions/checkout@v2


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'


      - name: Upgrade setuptools, wheel, and install requirements
        run: |
          pip install --upgrade setuptools wheel pyinstaller~=5.13.2 && pip install -r requirements.txt

      - name: Build playwright
        shell: bash
        if: matrix.config.os.filename != 'linux_amd64' && matrix.config.os.filename != 'linux_arm64'
        run: |
          PLAYWRIGHT_BROWSERS_PATH=0 playwright install chromium


      - name: Build Pyinstaller
        shell: bash
        run: |
          pyinstaller main.spec
      - name: Zip the Build-windows
        if: matrix.config.os.filename == 'windows_amd64'
        run: Compress-Archive -Path ./dist/biliTicKerBuy.exe -DestinationPath tmp.zip

      - name: Zip the Build-linux
        if: matrix.config.os.filename != 'windows_amd64'
        run: |
          cd ./dist
          zip -r  ../tmp.zip biliTickerBuy

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: tmp.zip
          asset_name: ${{ secrets.ReleaseZipName }}_${{ matrix.config.os.filename }}_${{ github.ref_name }}.zip
          tag: ${{ github.ref }}
          overwrite: true
